# Generated by Django 6.0.1 on 2026-08-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('manager', 'Manager'), ('employee', 'Employee'), ('sales', 'Sales'), ('inventory', 'Inventory'), ('finance', 'Finance')], default='employee', max_length=20),
        ),
    ]
