# Generated by Django 6.0.1 on 2026-04-20 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_days', models.IntegerField()),
                ('present_days', models.IntegerField()),
                ('half_days', models.IntegerField()),
                ('absent_days', models.IntegerField()),
                ('leave_days', models.IntegerField()),
                ('base_salary', models.FloatField()),
                ('final_salary', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
    ]
